stages:
  - test
  - build

go-test:
  stage: test
  image: golang:1.19-alpine3.17
  script:
    - sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
    - apk add --update make git build-base
    - go env -w GOPROXY="https://goproxy.cn,direct"
    - go env -w GO111MODULE=on
    - CGO_ENABLED=1 GOOS=linux go test -race -v ./...
  tags:
    - builder
  allow_failure: false

build_image_tag:
  stage: build
  script:
    - echo 使用 ${CI_COMMIT_REF_NAME} 版本构建镜像
    - export TAG_IMAGE_URI=icdss.biomind.com.cn/library/venus:${CI_COMMIT_REF_NAME}
    - docker build --compress -f Dockerfile -t ${TAG_IMAGE_URI} .
    - docker push  ${TAG_IMAGE_URI}
  allow_failure: false
  tags:
    - builder
  only:
    - tags

build_image_dev:
  stage: build
  script:
    - echo 使用 ${CI_COMMIT_SHORT_SHA} 版本构建镜像
    - export TAG_IMAGE_URI=icdss.biomind.com.cn/library/venus:${CI_COMMIT_SHORT_SHA}
    - docker build --compress -f Dockerfile -t ${TAG_IMAGE_URI} .
    - docker push  ${TAG_IMAGE_URI}
  allow_failure: false
  tags:
    - builder
  only:
    - pushes
