// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: service.proto

package pbservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	Register(ctx context.Context, in *RegisterServicesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Discovery(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (Service_DiscoveryClient, error)
	DiscoveryOnce(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DiscoveryServiceResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Register(ctx context.Context, in *RegisterServicesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/Service/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Discovery(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (Service_DiscoveryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], "/Service/Discovery", opts...)
	if err != nil {
		return nil, err
	}
	x := &serviceDiscoveryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Service_DiscoveryClient interface {
	Recv() (*DiscoveryServiceResponse, error)
	grpc.ClientStream
}

type serviceDiscoveryClient struct {
	grpc.ClientStream
}

func (x *serviceDiscoveryClient) Recv() (*DiscoveryServiceResponse, error) {
	m := new(DiscoveryServiceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serviceClient) DiscoveryOnce(ctx context.Context, in *ServiceInfo, opts ...grpc.CallOption) (*DiscoveryServiceResponse, error) {
	out := new(DiscoveryServiceResponse)
	err := c.cc.Invoke(ctx, "/Service/DiscoveryOnce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	Register(context.Context, *RegisterServicesRequest) (*emptypb.Empty, error)
	Discovery(*ServiceInfo, Service_DiscoveryServer) error
	DiscoveryOnce(context.Context, *ServiceInfo) (*DiscoveryServiceResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) Register(context.Context, *RegisterServicesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedServiceServer) Discovery(*ServiceInfo, Service_DiscoveryServer) error {
	return status.Errorf(codes.Unimplemented, "method Discovery not implemented")
}
func (UnimplementedServiceServer) DiscoveryOnce(context.Context, *ServiceInfo) (*DiscoveryServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscoveryOnce not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Register(ctx, req.(*RegisterServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Discovery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceInfo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).Discovery(m, &serviceDiscoveryServer{stream})
}

type Service_DiscoveryServer interface {
	Send(*DiscoveryServiceResponse) error
	grpc.ServerStream
}

type serviceDiscoveryServer struct {
	grpc.ServerStream
}

func (x *serviceDiscoveryServer) Send(m *DiscoveryServiceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Service_DiscoveryOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DiscoveryOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Service/DiscoveryOnce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DiscoveryOnce(ctx, req.(*ServiceInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Service_Register_Handler,
		},
		{
			MethodName: "DiscoveryOnce",
			Handler:    _Service_DiscoveryOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Discovery",
			Handler:       _Service_Discovery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
