// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2023-02-20 13:19:41.970422 +0800 CST m=+0.574101334
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/kv/{namespace}": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "配置列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbkv.ListKeysResponse"
                        }
                    }
                }
            }
        },
        "/kv/{namespace}/{key}": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "查看配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "配置key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbkv.KVItem"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "新增配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "配置key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbkv.KVItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbkv.KVItem"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "删除配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "配置key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    }
                }
            }
        },
        "/namespace": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "命名空间列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespacesListResponse"
                        }
                    }
                }
            }
        },
        "/namespace/{namespace}": {
            "post": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "新增命名空间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespaceItem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespaceItem"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "删除命名空间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    }
                }
            }
        },
        "/namespace/{namespace}/user": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "命名空间下用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespaceUserListResponse"
                        }
                    }
                }
            }
        },
        "/namespace/{namespace}/user/{uid}": {
            "post": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "命名空间下新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespaceUserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "namespace"
                ],
                "summary": "命名空间下删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbnamespace.NamespaceUserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/emptypb.Empty"
                        }
                    }
                }
            }
        },
        "/service/{namespace}": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "服务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbmicroservice.ListServicesResponse"
                        }
                    }
                }
            }
        },
        "/service/{namespace}/{service_name}": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "服务版本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务名称",
                        "name": "service_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbmicroservice.ListServiceVersionsResponse"
                        }
                    }
                }
            }
        },
        "/service/{namespace}/{service_name}/{service_version}": {
            "get": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service"
                ],
                "summary": "服务入口",
                "parameters": [
                    {
                        "type": "string",
                        "description": "命名空间",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务名称",
                        "name": "service_name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "服务版本",
                        "name": "service_version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbmicroservice.DiscoveryServiceResponse"
                        }
                    }
                }
            }
        },
        "/user/login/{uid}": {
            "post": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbuser.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbuser.UserInfo"
                        }
                    }
                }
            }
        },
        "/user/{uid}": {
            "put": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "修改密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbuser.UserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbuser.UserInfo"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Basic": []
                    }
                ],
                "description": "qiuzhi.lu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "参数",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pbuser.UserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pbuser.UserInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "emptypb.Empty": {
            "type": "object"
        },
        "pbkv.KVItem": {
            "type": "object",
            "required": [
                "data_type",
                "key",
                "namespace"
            ],
            "properties": {
                "data_type": {
                    "description": "@cTags: binding:\"required,oneof=json yaml toml properties text\"",
                    "type": "string",
                    "enum": [
                        "json",
                        "yaml",
                        "toml",
                        "properties",
                        "text"
                    ]
                },
                "key": {
                    "description": "@cTags: binding:\"required,min=3\"",
                    "type": "string",
                    "minLength": 3
                },
                "namespace": {
                    "description": "@cTags: binding:\"required,min=3\"",
                    "type": "string",
                    "minLength": 3
                },
                "update_time": {
                    "description": "最近更新时间",
                    "type": "string"
                },
                "updater": {
                    "description": "最近更新人",
                    "type": "string"
                },
                "value": {
                    "description": "数据值",
                    "type": "string"
                },
                "version": {
                    "description": "数据版本",
                    "type": "string"
                }
            }
        },
        "pbkv.ListKeysResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pbkv.KVItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pbmicroservice.DiscoveryServiceResponse": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "pbmicroservice.ListServiceVersionsResponse": {
            "type": "object",
            "properties": {
                "versions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "pbmicroservice.ListServicesResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "pbnamespace.NamespaceItem": {
            "type": "object",
            "required": [
                "namespace_cn"
            ],
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建人",
                    "type": "string"
                },
                "namespace_cn": {
                    "description": "@cTags: binding:\"required,min=3\"",
                    "type": "string",
                    "minLength": 3
                },
                "namespace_en": {
                    "description": "英文名称",
                    "type": "string"
                }
            }
        },
        "pbnamespace.NamespaceUserInfo": {
            "type": "object",
            "required": [
                "namespace",
                "uid"
            ],
            "properties": {
                "create_time": {
                    "description": "添加时间",
                    "type": "string"
                },
                "creator": {
                    "description": "创建者",
                    "type": "string"
                },
                "namespace": {
                    "description": "@cTags: binding:\"required,min=3\"",
                    "type": "string",
                    "minLength": 3
                },
                "role": {
                    "description": "角色，只读成员/空间管理员",
                    "type": "string"
                },
                "uid": {
                    "description": "@cTags: binding:\"required\"",
                    "type": "string"
                }
            }
        },
        "pbnamespace.NamespaceUserListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pbnamespace.NamespaceUserInfo"
                    }
                }
            }
        },
        "pbnamespace.NamespacesListResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/pbnamespace.NamespaceItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "pbuser.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "uid"
            ],
            "properties": {
                "password": {
                    "description": "@cTags: binding:\"required\"",
                    "type": "string"
                },
                "uid": {
                    "description": "@cTags: binding:\"required\"",
                    "type": "string"
                }
            }
        },
        "pbuser.UserInfo": {
            "type": "object",
            "required": [
                "password",
                "uid"
            ],
            "properties": {
                "create_time": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "name": {
                    "description": "用户名/显示名称",
                    "type": "string"
                },
                "password": {
                    "description": "@cTags: binding:\"required\"",
                    "type": "string"
                },
                "role": {
                    "description": "用户全局角色 普通成员/管理员",
                    "type": "string"
                },
                "status": {
                    "description": "用户状态",
                    "type": "integer"
                },
                "uid": {
                    "description": "@cTags: binding:\"required\"",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v1.0",
	Host:             "127.0.0.1:7233",
	BasePath:         "/api/v1",
	Schemes:          []string{"https", "http"},
	Title:            "venus",
	Description:      "统一对外输出的接口层,返回参数标准位json,结构为{\"code\":err code,\"msg\":\"提示信息\",\"data\":object\"}，文档中只展示data的结构",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
