// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: kv.proto

package pbkv

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KVServiceClient is the client API for KVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KVServiceClient interface {
	AddKV(ctx context.Context, in *KVItem, opts ...grpc.CallOption) (*KVItem, error)
	FetchKey(ctx context.Context, in *FetchKeyRequest, opts ...grpc.CallOption) (*KVItem, error)
	DelKey(ctx context.Context, in *DelKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	WatchKey(ctx context.Context, in *WatchKeyRequest, opts ...grpc.CallOption) (KVService_WatchKeyClient, error)
	WatchKeyClientList(ctx context.Context, in *WatchKeyClientListRequest, opts ...grpc.CallOption) (*WatchKeyClientListResponse, error)
}

type kVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKVServiceClient(cc grpc.ClientConnInterface) KVServiceClient {
	return &kVServiceClient{cc}
}

func (c *kVServiceClient) AddKV(ctx context.Context, in *KVItem, opts ...grpc.CallOption) (*KVItem, error) {
	out := new(KVItem)
	err := c.cc.Invoke(ctx, "/KVService/AddKV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) FetchKey(ctx context.Context, in *FetchKeyRequest, opts ...grpc.CallOption) (*KVItem, error) {
	out := new(KVItem)
	err := c.cc.Invoke(ctx, "/KVService/FetchKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) DelKey(ctx context.Context, in *DelKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KVService/DelKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, "/KVService/ListKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVServiceClient) WatchKey(ctx context.Context, in *WatchKeyRequest, opts ...grpc.CallOption) (KVService_WatchKeyClient, error) {
	stream, err := c.cc.NewStream(ctx, &KVService_ServiceDesc.Streams[0], "/KVService/WatchKey", opts...)
	if err != nil {
		return nil, err
	}
	x := &kVServiceWatchKeyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type KVService_WatchKeyClient interface {
	Recv() (*WatchKeyResponse, error)
	grpc.ClientStream
}

type kVServiceWatchKeyClient struct {
	grpc.ClientStream
}

func (x *kVServiceWatchKeyClient) Recv() (*WatchKeyResponse, error) {
	m := new(WatchKeyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *kVServiceClient) WatchKeyClientList(ctx context.Context, in *WatchKeyClientListRequest, opts ...grpc.CallOption) (*WatchKeyClientListResponse, error) {
	out := new(WatchKeyClientListResponse)
	err := c.cc.Invoke(ctx, "/KVService/WatchKeyClientList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KVServiceServer is the server API for KVService service.
// All implementations must embed UnimplementedKVServiceServer
// for forward compatibility
type KVServiceServer interface {
	AddKV(context.Context, *KVItem) (*KVItem, error)
	FetchKey(context.Context, *FetchKeyRequest) (*KVItem, error)
	DelKey(context.Context, *DelKeyRequest) (*emptypb.Empty, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	WatchKey(*WatchKeyRequest, KVService_WatchKeyServer) error
	WatchKeyClientList(context.Context, *WatchKeyClientListRequest) (*WatchKeyClientListResponse, error)
	mustEmbedUnimplementedKVServiceServer()
}

// UnimplementedKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKVServiceServer struct {
}

func (UnimplementedKVServiceServer) AddKV(context.Context, *KVItem) (*KVItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddKV not implemented")
}
func (UnimplementedKVServiceServer) FetchKey(context.Context, *FetchKeyRequest) (*KVItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchKey not implemented")
}
func (UnimplementedKVServiceServer) DelKey(context.Context, *DelKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelKey not implemented")
}
func (UnimplementedKVServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKVServiceServer) WatchKey(*WatchKeyRequest, KVService_WatchKeyServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchKey not implemented")
}
func (UnimplementedKVServiceServer) WatchKeyClientList(context.Context, *WatchKeyClientListRequest) (*WatchKeyClientListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WatchKeyClientList not implemented")
}
func (UnimplementedKVServiceServer) mustEmbedUnimplementedKVServiceServer() {}

// UnsafeKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KVServiceServer will
// result in compilation errors.
type UnsafeKVServiceServer interface {
	mustEmbedUnimplementedKVServiceServer()
}

func RegisterKVServiceServer(s grpc.ServiceRegistrar, srv KVServiceServer) {
	s.RegisterService(&KVService_ServiceDesc, srv)
}

func _KVService_AddKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KVItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).AddKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVService/AddKV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).AddKV(ctx, req.(*KVItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_FetchKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).FetchKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVService/FetchKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).FetchKey(ctx, req.(*FetchKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_DelKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).DelKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVService/DelKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).DelKey(ctx, req.(*DelKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVService/ListKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVService_WatchKey_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchKeyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KVServiceServer).WatchKey(m, &kVServiceWatchKeyServer{stream})
}

type KVService_WatchKeyServer interface {
	Send(*WatchKeyResponse) error
	grpc.ServerStream
}

type kVServiceWatchKeyServer struct {
	grpc.ServerStream
}

func (x *kVServiceWatchKeyServer) Send(m *WatchKeyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _KVService_WatchKeyClientList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchKeyClientListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVServiceServer).WatchKeyClientList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KVService/WatchKeyClientList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVServiceServer).WatchKeyClientList(ctx, req.(*WatchKeyClientListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KVService_ServiceDesc is the grpc.ServiceDesc for KVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KVService",
	HandlerType: (*KVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddKV",
			Handler:    _KVService_AddKV_Handler,
		},
		{
			MethodName: "FetchKey",
			Handler:    _KVService_FetchKey_Handler,
		},
		{
			MethodName: "DelKey",
			Handler:    _KVService_DelKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KVService_ListKeys_Handler,
		},
		{
			MethodName: "WatchKeyClientList",
			Handler:    _KVService_WatchKeyClientList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchKey",
			Handler:       _KVService_WatchKey_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kv.proto",
}
