// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: config.proto

package pbconfig

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigServiceClient is the client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigServiceClient interface {
	AddOrUpdateOidc(ctx context.Context, in *Oidc, opts ...grpc.CallOption) (*Oidc, error)
	ChangeOidcStatus(ctx context.Context, in *ChangeOidcStatusRequest, opts ...grpc.CallOption) (*Oidc, error)
	LoadOidcConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Oidc, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) AddOrUpdateOidc(ctx context.Context, in *Oidc, opts ...grpc.CallOption) (*Oidc, error) {
	out := new(Oidc)
	err := c.cc.Invoke(ctx, "/ConfigService/AddOrUpdateOidc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) ChangeOidcStatus(ctx context.Context, in *ChangeOidcStatusRequest, opts ...grpc.CallOption) (*Oidc, error) {
	out := new(Oidc)
	err := c.cc.Invoke(ctx, "/ConfigService/ChangeOidcStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configServiceClient) LoadOidcConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Oidc, error) {
	out := new(Oidc)
	err := c.cc.Invoke(ctx, "/ConfigService/LoadOidcConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the server API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forward compatibility
type ConfigServiceServer interface {
	AddOrUpdateOidc(context.Context, *Oidc) (*Oidc, error)
	ChangeOidcStatus(context.Context, *ChangeOidcStatusRequest) (*Oidc, error)
	LoadOidcConfig(context.Context, *emptypb.Empty) (*Oidc, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedConfigServiceServer struct {
}

func (UnimplementedConfigServiceServer) AddOrUpdateOidc(context.Context, *Oidc) (*Oidc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdateOidc not implemented")
}
func (UnimplementedConfigServiceServer) ChangeOidcStatus(context.Context, *ChangeOidcStatusRequest) (*Oidc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeOidcStatus not implemented")
}
func (UnimplementedConfigServiceServer) LoadOidcConfig(context.Context, *emptypb.Empty) (*Oidc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadOidcConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}

// UnsafeConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_AddOrUpdateOidc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Oidc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).AddOrUpdateOidc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ConfigService/AddOrUpdateOidc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).AddOrUpdateOidc(ctx, req.(*Oidc))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_ChangeOidcStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeOidcStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).ChangeOidcStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ConfigService/ChangeOidcStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).ChangeOidcStatus(ctx, req.(*ChangeOidcStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigService_LoadOidcConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).LoadOidcConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ConfigService/LoadOidcConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).LoadOidcConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrUpdateOidc",
			Handler:    _ConfigService_AddOrUpdateOidc_Handler,
		},
		{
			MethodName: "ChangeOidcStatus",
			Handler:    _ConfigService_ChangeOidcStatus_Handler,
		},
		{
			MethodName: "LoadOidcConfig",
			Handler:    _ConfigService_LoadOidcConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
